Repository AzuraMC-Network/AzuraBedWars, pull requests merged in 2025-08, with the labels that each got.

#84 Merge Develop
  1_8_R3/src/main/java/cc/azuramc/bedwars/nms/CustomIronGolem.java
  1_8_R3/src/main/java/cc/azuramc/bedwars/nms/CustomSilverfish.java
  core/src/main/java/cc/azuramc/bedwars/event/AbstractGameEvent.java
  core/src/main/java/cc/azuramc/bedwars/event/impl/DiamondUpdateEvent.java
  core/src/main/java/cc/azuramc/bedwars/event/impl/EmeraldUpdateEvent.java
  core/src/main/java/cc/azuramc/bedwars/game/CustomEntityManager.java
  core/src/main/java/cc/azuramc/bedwars/game/GamePlayer.java
  core/src/main/java/cc/azuramc/bedwars/gui/base/listener/GUIListener.java
  core/src/main/java/cc/azuramc/bedwars/listener/ListenerRegistry.java
  core/src/main/java/cc/azuramc/bedwars/listener/player/PlayerDrinkMilkListener.java
  core/src/main/java/cc/azuramc/bedwars/listener/player/PlayerFastPutListener.java
  core/src/main/java/cc/azuramc/bedwars/listener/player/PlayerUseBucketListener.java
  core/src/main/java/cc/azuramc/bedwars/listener/special/EntityDeathListener.java
  core/src/main/java/cc/azuramc/bedwars/listener/special/RescuePlatformListener.java
  core/src/main/java/cc/azuramc/bedwars/listener/special/SilverFishListener.java
  core/src/main/java/cc/azuramc/bedwars/shop/gui/ItemShopGUI.java
  core/src/main/java/cc/azuramc/bedwars/shop/gui/TeamShopGUI.java
  core/src/main/java/cc/azuramc/bedwars/shop/page/PotionShopPage.java
Labels: 🔄 Sync

#90 Sync develop branch
  core/src/main/java/cc/azuramc/bedwars/listener/player/PlayerDamageListener.java
Labels: 🔄 Sync

#91 [Release] v1.0.0-beta.5
  .github/workflows/auto-manager.yml
  build.gradle
  core/src/main/java/cc/azuramc/bedwars/config/object/EventConfig.java
  core/src/main/java/cc/azuramc/bedwars/event/GameEventManager.java
  core/src/main/java/cc/azuramc/bedwars/event/impl/GameStartEvent.java
  core/src/main/java/cc/azuramc/bedwars/game/CustomEntityManager.java
  core/src/main/java/cc/azuramc/bedwars/game/GameManager.java
  core/src/main/java/cc/azuramc/bedwars/game/GamePlayer.java
  core/src/main/java/cc/azuramc/bedwars/game/GameTeam.java
  core/src/main/java/cc/azuramc/bedwars/gui/base/CustomGUI.java
  core/src/main/java/cc/azuramc/bedwars/gui/base/listener/GUIListener.java
  core/src/main/java/cc/azuramc/bedwars/listener/player/PickupItemHandler.java
  core/src/main/java/cc/azuramc/bedwars/listener/player/PlayerDamageListener.java
  core/src/main/java/cc/azuramc/bedwars/listener/player/PlayerDeathReasonListener.java
  core/src/main/java/cc/azuramc/bedwars/shop/gui/ItemShopGUI.java
  core/src/main/java/cc/azuramc/bedwars/shop/gui/TeamShopGUI.java
  core/src/main/java/cc/azuramc/bedwars/upgrade/factory/TrapStrategyFactory.java
  core/src/main/java/cc/azuramc/bedwars/upgrade/factory/UpgradeStrategyFactory.java
  core/src/main/java/cc/azuramc/bedwars/upgrade/task/TeamUpgradeCheckTask.java
  core/src/main/java/cc/azuramc/bedwars/upgrade/trap/AbstractTrapStrategy.java
  core/src/main/java/cc/azuramc/bedwars/upgrade/trap/TrapManager.java
  core/src/main/java/cc/azuramc/bedwars/upgrade/trap/TrapState.java
  core/src/main/java/cc/azuramc/bedwars/upgrade/trap/TrapStrategy.java
  core/src/main/java/cc/azuramc/bedwars/upgrade/trap/TrapType.java
  core/src/main/java/cc/azuramc/bedwars/upgrade/trap/impl/AlarmTrapStrategy.java
  core/src/main/java/cc/azuramc/bedwars/upgrade/trap/impl/BlindnessTrapStrategy.java
  core/src/main/java/cc/azuramc/bedwars/upgrade/trap/impl/FightBackTrapStrategy.java
  core/src/main/java/cc/azuramc/bedwars/upgrade/trap/impl/MinerTrapStrategy.java
  core/src/main/java/cc/azuramc/bedwars/upgrade/upgrade/AbstractTieredUpgradeStrategy.java
  core/src/main/java/cc/azuramc/bedwars/upgrade/upgrade/AbstractUpgradeStrategy.java
  core/src/main/java/cc/azuramc/bedwars/upgrade/upgrade/UpgradeManager.java
  core/src/main/java/cc/azuramc/bedwars/upgrade/upgrade/UpgradeStrategy.java
  core/src/main/java/cc/azuramc/bedwars/upgrade/upgrade/impl/FallingProtectionUpgradeStrategyAbstract.java
  core/src/main/java/cc/azuramc/bedwars/upgrade/upgrade/impl/HealingPoolUpgradeStrategy.java
  core/src/main/java/cc/azuramc/bedwars/upgrade/upgrade/impl/ManicMinerUpgradeStrategyAbstract.java
  core/src/main/java/cc/azuramc/bedwars/upgrade/upgrade/impl/ReinforcedArmorUpgradeStrategyAbstract.java
  core/src/main/java/cc/azuramc/bedwars/upgrade/upgrade/impl/ResourceFurnaceUpgradeStrategyAbstract.java
  core/src/main/java/cc/azuramc/bedwars/upgrade/upgrade/impl/SharpenedSwordsUpgradeStrategy.java
Labels: 🚀 Release

#98 Merge Develop
  core/src/main/java/cc/azuramc/bedwars/compat/VersionUtil.java
  core/src/main/java/cc/azuramc/bedwars/compat/util/PlayerUtil.java
  core/src/main/java/cc/azuramc/bedwars/game/GamePlayer.java
  core/src/main/java/cc/azuramc/bedwars/listener/player/PlayerDrinkMilkListener.java
  core/src/main/java/cc/azuramc/bedwars/listener/player/PlayerInvisibilityListener.java
  core/src/main/java/cc/azuramc/bedwars/listener/player/PlayerUseBucketListener.java
Labels: 🐛 Bug Fix, ✨ New Feature, 🔄 Sync

#109 fix: add PR state check to skip closed PRs and prevent 🚧 Work in Prog…
  .github/workflows/auto-manager.yml
Labels: 🐛 Bug Fix, 🔄 Sync, 👷 CI, 🚧 Work in Progress
